//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGet.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuGet.Client.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install failed. Rolling back....
        /// </summary>
        internal static string ActionExecutor_RollingBack {
            get {
                return ResourceManager.GetString("ActionExecutor_RollingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized Package Action &apos;{0}&apos;..
        /// </summary>
        internal static string ActionResolver_UnsupportedAction {
            get {
                return ResourceManager.GetString("ActionResolver_UnsupportedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Dependency Behavior &apos;{0}&apos;..
        /// </summary>
        internal static string ActionResolver_UnsupportedDependencyBehavior {
            get {
                return ResourceManager.GetString("ActionResolver_UnsupportedDependencyBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download URL for {0} &apos;{1}&apos; is invalid. {2}.
        /// </summary>
        internal static string DownloadActionHandler_InvalidDownloadUrl {
            get {
                return ResourceManager.GetString("DownloadActionHandler_InvalidDownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No download URL could be found for {0}..
        /// </summary>
        internal static string DownloadActionHandler_NoDownloadUrl {
            get {
                return ResourceManager.GetString("DownloadActionHandler_NoDownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a NuGet Repository from the Aggregate Source.
        /// </summary>
        internal static string NuGetRepository_CannotCreateAggregateRepo {
            get {
                return ResourceManager.GetString("NuGetRepository_CannotCreateAggregateRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} service is not supported by this object..
        /// </summary>
        internal static string NuGetServiceProvider_ServiceNotSupported {
            get {
                return ResourceManager.GetString("NuGetServiceProvider_ServiceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized Package Action &apos;{0}&apos;..
        /// </summary>
        internal static string PackageActionDescriptionWrapper_UnrecognizedAction {
            get {
                return ResourceManager.GetString("PackageActionDescriptionWrapper_UnrecognizedAction", resourceCulture);
            }
        }
    }
}
