//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGet.Dialog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuGet.Dialog.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string Dialog_Close {
            get {
                return ResourceManager.GetString("Dialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by:.
        /// </summary>
        public static string Dialog_CreatedByLabel {
            get {
                return ResourceManager.GetString("Dialog_CreatedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies:.
        /// </summary>
        public static string Dialog_DependenciesLabel {
            get {
                return ResourceManager.GetString("Dialog_DependenciesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads:.
        /// </summary>
        public static string Dialog_DownloadsLabel {
            get {
                return ResourceManager.GetString("Dialog_DownloadsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        public static string Dialog_IdLabel {
            get {
                return ResourceManager.GetString("Dialog_IdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Install.
        /// </summary>
        public static string Dialog_InstallButton {
            get {
                return ResourceManager.GetString("Dialog_InstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed packages.
        /// </summary>
        public static string Dialog_InstalledProvider {
            get {
                return ResourceManager.GetString("Dialog_InstalledProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No packages are installed in the current project..
        /// </summary>
        public static string Dialog_InstalledProviderNoItem {
            get {
                return ResourceManager.GetString("Dialog_InstalledProviderNoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string Dialog_InstallProgress {
            get {
                return ResourceManager.GetString("Dialog_InstallProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated:.
        /// </summary>
        public static string Dialog_LastUpdatedLabel {
            get {
                return ResourceManager.GetString("Dialog_LastUpdatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        public static string Dialog_MessageBoxTitle {
            get {
                return ResourceManager.GetString("Dialog_MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Information.
        /// </summary>
        public static string Dialog_MoreInfo {
            get {
                return ResourceManager.GetString("Dialog_MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Dependencies.
        /// </summary>
        public static string Dialog_NoDependencyLabel {
            get {
                return ResourceManager.GetString("Dialog_NoDependencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Dialog_OnlineProvider {
            get {
                return ResourceManager.GetString("Dialog_OnlineProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No packages found in the current package source..
        /// </summary>
        public static string Dialog_OnlineProviderNoItem {
            get {
                return ResourceManager.GetString("Dialog_OnlineProviderNoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed..
        /// </summary>
        public static string Dialog_OperationFailed {
            get {
                return ResourceManager.GetString("Dialog_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each item above may have sub-dependencies subject to additional license agreements..
        /// </summary>
        public static string Dialog_PackageDisclaimer {
            get {
                return ResourceManager.GetString("Dialog_PackageDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This package (or one of its dependencies) contains PowerShell scripts but the PowerShell 2.0 (or newer) runtime is not installed on this machine..
        /// </summary>
        public static string Dialog_PackageHasPSScript {
            get {
                return ResourceManager.GetString("Dialog_PackageHasPSScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This package is already installed..
        /// </summary>
        public static string Dialog_PackageInstalledTooltip {
            get {
                return ResourceManager.GetString("Dialog_PackageInstalledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This package is already updated..
        /// </summary>
        public static string Dialog_PackageUpdatedTooltip {
            get {
                return ResourceManager.GetString("Dialog_PackageUpdatedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate It.
        /// </summary>
        public static string Dialog_RateItLabel {
            get {
                return ResourceManager.GetString("Dialog_RateItLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating:.
        /// </summary>
        public static string Dialog_RatingLabel {
            get {
                return ResourceManager.GetString("Dialog_RatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f1} stars.
        /// </summary>
        public static string Dialog_RatingTooltip {
            get {
                return ResourceManager.GetString("Dialog_RatingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Recent.
        /// </summary>
        public static string Dialog_RecentPackagesDefaultSort {
            get {
                return ResourceManager.GetString("Dialog_RecentPackagesDefaultSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent packages.
        /// </summary>
        public static string Dialog_RecentProvider {
            get {
                return ResourceManager.GetString("Dialog_RecentProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no recently installed packages..
        /// </summary>
        public static string Dialog_RecentProviderNoItem {
            get {
                return ResourceManager.GetString("Dialog_RecentProviderNoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Abuse.
        /// </summary>
        public static string Dialog_ReportAbuse {
            get {
                return ResourceManager.GetString("Dialog_ReportAbuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Dialog_RootNodeAll {
            get {
                return ResourceManager.GetString("Dialog_RootNodeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string Dialog_RootNodeSearch {
            get {
                return ResourceManager.GetString("Dialog_RootNodeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string Dialog_Settings {
            get {
                return ResourceManager.GetString("Dialog_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Dialog_SortAscending {
            get {
                return ResourceManager.GetString("Dialog_SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Dialog_SortDescending {
            get {
                return ResourceManager.GetString("Dialog_SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Rated.
        /// </summary>
        public static string Dialog_SortOption_HighestRated {
            get {
                return ResourceManager.GetString("Dialog_SortOption_HighestRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Downloads.
        /// </summary>
        public static string Dialog_SortOption_MostDownloads {
            get {
                return ResourceManager.GetString("Dialog_SortOption_MostDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Dialog_SortOption_Name {
            get {
                return ResourceManager.GetString("Dialog_SortOption_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags:.
        /// </summary>
        public static string Dialog_TagLabel {
            get {
                return ResourceManager.GetString("Dialog_TagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Library Package Reference.
        /// </summary>
        public static string Dialog_Title {
            get {
                return ResourceManager.GetString("Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Uninstall.
        /// </summary>
        public static string Dialog_UninstallButton {
            get {
                return ResourceManager.GetString("Dialog_UninstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        public static string Dialog_UninstallProgress {
            get {
                return ResourceManager.GetString("Dialog_UninstallProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Update.
        /// </summary>
        public static string Dialog_UpdateButton {
            get {
                return ResourceManager.GetString("Dialog_UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string Dialog_UpdateProgress {
            get {
                return ResourceManager.GetString("Dialog_UpdateProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Dialog_UpdateProvider {
            get {
                return ResourceManager.GetString("Dialog_UpdateProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No package updates are available from the selected package source..
        /// </summary>
        public static string Dialog_UpdatesProviderNoItem {
            get {
                return ResourceManager.GetString("Dialog_UpdatesProviderNoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Dialog_VersionLabel {
            get {
                return ResourceManager.GetString("Dialog_VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} Votes).
        /// </summary>
        public static string Dialog_VotesCount {
            get {
                return ResourceManager.GetString("Dialog_VotesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I _Accept.
        /// </summary>
        public static string License_Accept {
            get {
                return ResourceManager.GetString("License_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Author: {0}).
        /// </summary>
        public static string License_AuthorFormatString {
            get {
                return ResourceManager.GetString("License_AuthorFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I _Decline.
        /// </summary>
        public static string License_Decline {
            get {
                return ResourceManager.GetString("License_Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Acceptance.
        /// </summary>
        public static string License_DialogTitle {
            get {
                return ResourceManager.GetString("License_DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following package(s) require a click-to-accept license:.
        /// </summary>
        public static string License_HeaderText {
            get {
                return ResourceManager.GetString("License_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &quot;I Accept,&quot; you agree to the license terms for the package(s) listed above. If you do not agree to the license terms, click &quot;I Decline.&quot;.
        /// </summary>
        public static string License_LicenseText {
            get {
                return ResourceManager.GetString("License_LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View License Terms.
        /// </summary>
        public static string License_ViewLicense {
            get {
                return ResourceManager.GetString("License_ViewLicense", resourceCulture);
            }
        }
    }
}
