//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGet.Dialog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuGet.Dialog.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string Dialog_Close {
            get {
                return ResourceManager.GetString("Dialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by:.
        /// </summary>
        public static string Dialog_CreatedByLabel {
            get {
                return ResourceManager.GetString("Dialog_CreatedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies:.
        /// </summary>
        public static string Dialog_DependenciesLabel {
            get {
                return ResourceManager.GetString("Dialog_DependenciesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Install.
        /// </summary>
        public static string Dialog_InstallButton {
            get {
                return ResourceManager.GetString("Dialog_InstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed packages.
        /// </summary>
        public static string Dialog_InstalledProvider {
            get {
                return ResourceManager.GetString("Dialog_InstalledProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        public static string Dialog_MessageBoxTitle {
            get {
                return ResourceManager.GetString("Dialog_MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Information.
        /// </summary>
        public static string Dialog_MoreInfo {
            get {
                return ResourceManager.GetString("Dialog_MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string Dialog_NoDependencyLabel {
            get {
                return ResourceManager.GetString("Dialog_NoDependencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Dialog_OnlineProvider {
            get {
                return ResourceManager.GetString("Dialog_OnlineProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each item above may have sub-dependencies subject to additional license agreements..
        /// </summary>
        public static string Dialog_PackageDisclaimer {
            get {
                return ResourceManager.GetString("Dialog_PackageDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This package is already installed..
        /// </summary>
        public static string Dialog_PackageInstalledTooltip {
            get {
                return ResourceManager.GetString("Dialog_PackageInstalledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This package is already updated..
        /// </summary>
        public static string Dialog_PackageUpdatedTooltip {
            get {
                return ResourceManager.GetString("Dialog_PackageUpdatedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Dialog_RootNodeAll {
            get {
                return ResourceManager.GetString("Dialog_RootNodeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string Dialog_RootNodeSearch {
            get {
                return ResourceManager.GetString("Dialog_RootNodeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string Dialog_Settings {
            get {
                return ResourceManager.GetString("Dialog_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Library Package Reference.
        /// </summary>
        public static string Dialog_Title {
            get {
                return ResourceManager.GetString("Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Uninstall.
        /// </summary>
        public static string Dialog_UninstallButton {
            get {
                return ResourceManager.GetString("Dialog_UninstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Update.
        /// </summary>
        public static string Dialog_UpdateButton {
            get {
                return ResourceManager.GetString("Dialog_UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Dialog_UpdateProvider {
            get {
                return ResourceManager.GetString("Dialog_UpdateProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Dialog_VersionLabel {
            get {
                return ResourceManager.GetString("Dialog_VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I _Accept.
        /// </summary>
        public static string License_Accept {
            get {
                return ResourceManager.GetString("License_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I _Decline.
        /// </summary>
        public static string License_Decline {
            get {
                return ResourceManager.GetString("License_Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following package(s) require a click-to-accept license:.
        /// </summary>
        public static string License_HeaderText {
            get {
                return ResourceManager.GetString("License_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &quot;I Accept,&quot; you agree to the license terms for the package(s) listed above. If you do not agree to the license terms, click &quot;I Decline.&quot;.
        /// </summary>
        public static string License_LicenseText {
            get {
                return ResourceManager.GetString("License_LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View License Terms.
        /// </summary>
        public static string License_ViewLicense {
            get {
                return ResourceManager.GetString("License_ViewLicense", resourceCulture);
            }
        }
    }
}
